name: Continuous Integration

on:
  push:
  pull_request:

jobs:
  default-ci:
    name: JS CI Defaults
    uses: ucm-it/.github/.github/workflows/common-ci-js.yml@main
    permissions:
      contents: read
    with:
      node-version: '20.x'
    secrets:
      node-auth-token: ${{ secrets.GH_PKG_READ }}
