name: Update Browserslist database

on:
  schedule:
    # Run at 2:00 AM on the 1st and 15th of every month
    # https://crontab.guru/#0_2_1,15_*_*
    - cron: '0 2 1,15 * *'
  workflow_dispatch:

jobs:
  update-bl-database:
    name: Browserlist DB
    uses: ucm-it/.github/.github/workflows/update-browserlist.yml@main
    permissions:
      contents: write
      pull-requests: write
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
