name: npm Monorepo Package Publishing

on:
  push:
    branches:
      - $default-branch
    tags:
      - '**'

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#permissions
permissions:
  contents: write
  packages: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Publish Packages
        uses: ucm-it/npm-smart-publish@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude: |
            tsconfig
