name: JS CI Defaults

on:
  workflow_call:
    inputs:
      disable-formatting:
        required: false
        type: boolean
        default: false
      disable-linting:
        required: false
        type: boolean
        default: false
      disable-testing:
        required: false
        type: boolean
        default: false
      node-version:
        required: true
        type: string
        default: '20.x'
    secrets:
      node-auth-token:
        required: true

jobs:
  linting:
    name: Linting
    if: ${{ inputs.disable-linting != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ucm-it'
          always-auth: true

      - name: actionlint
        uses: raven-actions/actionlint@v2
        with:
          pyflakes: false

      - name: Install packages and run linters
        env:
          NODE_AUTH_TOKEN: ${{ secrets.node-auth-token }}
        run: |
          npm ci
          npm run lint
 
  formatter:
    name: Formatting
    if: ${{ inputs.disable-formatting != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ucm-it'
          always-auth: true

      - name: Install shfmt for formatting
        uses: mfinelli/setup-shfmt@v3

      - name: Install dependency packages and run formatters
        env:
          NODE_AUTH_TOKEN: ${{ secrets.node-auth-token }}
        run: |
          npm ci
          npm run format
          git diff --exit-code

  unit_test:
    name: Unit Testing
    if: ${{ inputs.disable-testing != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ucm-it'
          always-auth: true

      - name: Install dependency packages and run unit tests
        env:
          NODE_AUTH_TOKEN: ${{ secrets.node-auth-token }}
        run: |
          npm ci
          npm run build
          npm run test
